### ISSUE TITLE
How to solve the question in the picture

### ISSUE THREAD

**Issue by lu592674374** [Racle/Dockerfiles#1]
![image](https://user-images.githubusercontent.com/15523855/40375143-4c0a81e0-5e1d-11e8-8d36-6341ac99f638.png)

**Comment by Racle** [comment]
Did you run
`xhost +local:docker` before that command?
I might forgot to add that to Readme, but that is from `rdm.sh` file :)

And if you happen to use Wayland, there might be workaround for that, quick googling shows that it probably won't work right away. 
I use xorg, as default in Ubuntu 16.04, and it works without any extra work.

**Comment by lu592674374** [comment]
success, Thanks.

**Comment by Racle** [comment]
Awesome.
I'll add that to manual part.
