### ISSUE TITLE
Ubuntu 18 Compatible

### ISSUE THREAD

**Issue by BlackMetalz** [Racle/Dockerfiles#2]
Hi, i just try to install this to ubuntu 18 desktop and seem like it doesn't work when i try to click into Redis desktop manager icon, does this work on ubuntu 18? :D

**Comment by BlackMetalz** [comment]
non-network local connections being added to access control list
Error response from daemon: No such container: redis-desktop-manager
Error response from daemon: No such container: redis-desktop-manager
docker: Error response from daemon: invalid volume spec ":": invalid volume specification: ':'.
See 'docker run --help'.


here is what output when i'm run rdm on terminal

**Comment by Racle** [comment]
It should work. Got co-worker which uses Ubuntu 18.04 and we just tested that it works. I'm currently running 16.04, and plan to switch after 18.04.1 update :P (so little hard to debug)

It seems like script cannot (for some reason) get volume correctly.. (docker: Error response from daemon: invalid volume spec ":": invalid volume specification: ':'.)
Other errors are normal.

Can you try manual commands and see if that works? just run these from terminal

```
xhost +local:docker
docker run  -it --rm \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.rdm:/root/.rdm \
    -e DISPLAY \
    --device /dev/dri \
    -e SSH_AUTH_SOCK \
    -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK \
    --name redis-desktop-manager \
    racle90/redis-desktop-manager
```
If manual way works, there is something odd with rdm script then. Maybe wget+github corrupts something there :/ (it's happened before).

One fix could be this:
Copy-paste following code https://raw.githubusercontent.com/Racle/Dockerfiles/master/redis-desktop-manager/rdm.sh
to `/usr/share/redis-desktop-manager/rdm.sh`. this _could_ fix the corrupt part of script, but not 100% sure.

**Comment by BlackMetalz** [comment]
![image](https://user-images.githubusercontent.com/3434274/41706699-a3d1dcc4-7566-11e8-851f-4ddddef19b2a.png)
i copy-paste ur fixes 
i tried both with Ubuntu 17 & 18 on VMware, not sure if it is reason make script is not working :(

**Comment by Racle** [comment]
Well. It seems that $SSH_AUTH_SOCK is not defined (after reading error message once more).
(And it's usually required when connecting to redis host with ssl enabled).

If you don't need ssl support, drop the ssh lines. I've tested this with my machine, and it works without those lines. 

So modify file `/usr/share/redis-desktop-manager/rdm.sh`
to look like this:
```
#!/bin/sh
xhost +local:docker
docker stop redis-desktop-manager
docker rm redis-desktop-manager
docker run --rm \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.rdm:/root/.rdm \
    -e DISPLAY \
    --device /dev/dri \
    --name redis-desktop-manager \
    racle90/redis-desktop-manager
```

it _should_ work with icon and rdm command after that. At least I hope so :sweat_smile: 

EDIT: you can try to run that within terminal also to test it out. Might be faster to test than editing a file.

**Comment by BlackMetalz** [comment]
Yeah, maybe my Ubuntu got corrupted somehow, i tried again in another computer running Ubuntu 18 and it works. Thank you

P/s: You can close this issue :dancer:

**Comment by Racle** [comment]
Glad you got that working with other machine. 

It might be missing openssl install or something.
